kingdom_hall_api:
    resource: "@KingdomHallApiBundle/Resources/config/routing.yml"

kingdom_hall_tasks:
    resource: "@KingdomHallServiceBundle/Resources/config/routing.yml"

kingdom_hall_cron:
    resource: "@KingdomHallTaskBundle/Resources/config/routing.yml"

kingdom_hall_main:
    resource: "@KingdomHallMainBundle/Resources/config/routing.yml"

fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /{_locale}/profile

fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /register

#fos_user_resetting:
#    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
#    prefix: /resetting
#
#fos_user_password:
#    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
#    prefix: /profile

# Fallbacks
kingdom_hall_fallback_home:
    path: /{_locale}/{congregationCode}
    defaults: { _controller: KingdomHallMainBundle:Home:index }

kingdom_hall_fallback_locale:
    path: /{_locale}
    defaults: { _controller: KingdomHallMainBundle:Fallback:fallback }

kingdom_hall_fallback:
    path:     /
    defaults: { _controller: KingdomHallMainBundle:Fallback:fallback }
