kingdom_hall_api_territories:
    prefix: /api
    type: rest
    resource: KingdomHall\ApiBundle\Controller\TerritoryController

kingdom_hall_api_campaigns:
    prefix: /api
    type: rest
    resource: KingdomHall\ApiBundle\Controller\CampaignController

