kingdom_hall_api_territories:
    prefix: /api
    type: rest
    resource: KingdomHall\ApiBundle\Controller\TerritoryController

kingdom_hall_api_campaigns:
    prefix: /api
    type: rest
    resource: KingdomHall\ApiBundle\Controller\CampaignController

kingdom_hall_api_publishers:
    prefix: /api
    type: rest
    resource: KingdomHall\ApiBundle\Controller\PublisherController

kingdom_hall_api_users:
    prefix: /api
    type: rest
    resource: KingdomHall\ApiBundle\Controller\UserController

