############
# Homepage #
############

kingdom_hall_homepage:
    path:     /{_locale}/{congregationCode}/home
    defaults: { _locale: en, _controller: KingdomHallMainBundle:Home:index }

###############
# Territories #
###############

# List

kingdom_hall_territories_list:
    path:     /{_locale}/{congregationCode}/territories
    defaults: { _locale: en, _controller: KingdomHallMainBundle:Territory/List:index }

kingdom_hall_territories_new:
    path:     /{_locale}/{congregationCode}/territories/new
    defaults: { _locale: en, _controller: KingdomHallMainBundle:Territory/List:new }

kingdom_hall_territories_edit:
    path:     /{_locale}/{congregationCode}/territories/{territoryId}/edit
    defaults: { _locale: en, _controller: KingdomHallMainBundle:Territory/List:edit }

kingdom_hall_territories_borrow:
    path:     /{_locale}/{congregationCode}/territories/{territoryId}/borrow
    defaults: { _locale: en, _controller: KingdomHallMainBundle:Territory/List:borrow }

kingdom_hall_territories_return:
    path:     /{_locale}/{congregationCode}/territories/{territoryId}/return
    defaults: { _locale: en, _controller: KingdomHallMainBundle:Territory/List:return }

kingdom_hall_territories_forward:
    path:     /{_locale}/{congregationCode}/territories/{territoryId}/forward
    defaults: { _locale: en, _controller: KingdomHallMainBundle:Territory/List:forward }

kingdom_hall_territories_novisit_edit:
    path:     /{_locale}/{congregationCode}/territories/{territoryId}/novisit/{noVisitId}/edit
    defaults: { _locale: en, _controller: KingdomHallMainBundle:Territory/List:editNoVisit, noVisitId: 0 }

kingdom_hall_territories_history_edit:
    path:     /{_locale}/{congregationCode}/territories/{territoryId}/history/{historyId}/edit
    defaults: { _locale: en, _controller: KingdomHallMainBundle:Territory/List:editHistory, historyId: 0 }

kingdom_hall_territories_view:
    path:     /{_locale}/{congregationCode}/territories/{territoryId}/view
    defaults: { _locale: en, _controller: KingdomHallMainBundle:Territory/List:view }

kingdom_hall_territories_print:
    path:     /{_locale}/{congregationCode}/territories/{territoryId}/print
    defaults: { _locale: en, _controller: KingdomHallMainBundle:Territory/List:print }

kingdom_hall_territories_s13:
    path:     /{_locale}/{congregationCode}/territories/s13
    defaults: { _locale: en, _controller: KingdomHallMainBundle:Territory/List:s13 }

kingdom_hall_territories_s13_download:
    path:     /{_locale}/{congregationCode}/territories/s13/pdf
    defaults: { _locale: en, _controller: KingdomHallMainBundle:Territory/List:s13Pdf }

# Campaigns

kingdom_hall_campaigns_list:
    path:     /{_locale}/{congregationCode}/campaigns
    defaults: { _locale: en, _controller: KingdomHallMainBundle:Territory/Campaign:index }

kingdom_hall_campaigns_new:
    path:     /{_locale}/{congregationCode}/campaigns/new
    defaults: { _locale: en, _controller: KingdomHallMainBundle:Territory/Campaign:new }

kingdom_hall_campaigns_edit:
    path:     /{_locale}/{congregationCode}/campaigns/{campaignId}/edit
    defaults: { _locale: en, _controller: KingdomHallMainBundle:Territory/Campaign:edit }

# Admin

# Settings
kingdom_hall_settings:
    path:     /{_locale}/{congregationCode}/settings
    defaults: { _locale: en, _controller: KingdomHallMainBundle:Admin/Settings:index }

# Users
kingdom_hall_users_list:
    path:     /{_locale}/{congregationCode}/users
    defaults: { _locale: en, _controller: KingdomHallMainBundle:Admin/User:list }

kingdom_hall_users_edit:
    path:     /{_locale}/{congregationCode}/users/{userId}/edit
    defaults: { _locale: en, _controller: KingdomHallMainBundle:Admin/User:edit, userId: 0 }

# Publishers

kingdom_hall_publishers_list:
    path:     /{_locale}/{congregationCode}/publishers
    defaults: { _locale: en, _controller: KingdomHallMainBundle:Publisher:list }

kingdom_hall_publishers_edit:
    path:     /{_locale}/{congregationCode}/publishers/{publisherId}/edit
    defaults: { _locale: en, _controller: KingdomHallMainBundle:Publisher:edit, publisherId: 0 }


##########
# Modals #
##########

kingdom_hall_modal_confirmation:
    path:     /{_locale}/modal/confirmation
    defaults: { _locale: en, _controller: KingdomHallMainBundle:Modal:confirmationModal }

kingdom_hall_modal_info:
    path:     /{_locale}/modal/info
    defaults: { _locale: en, _controller: KingdomHallMainBundle:Modal:infoModal }
